export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            Dashboard header
            <body>{children}</body>
        </html>
    );
}
